version: '2'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: apnicuser
      WORDPRESS_DB_PASSWORD: apnicpassword
      WORDPRESS_DB_NAME: apnic
    volumes:
      - ./wordpress:/var/www/html:delegated
    links:
      - db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=apnic
      - MYSQL_USER=apnicuser
      - MYSQL_PASSWORD=apnicpassword
      - MYSQL_ROOT_PASSWORD=apnicrootpassword
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:delegated
volumes:
  wordpress:
  db:
